name: Build and publish docker image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/nogesma/cube-bot-web:latest
          build-args: |
            VITE_REDIRECT_URI=https://cube.sfk5.fyi/
            VITE_CLIENT_ID=475749622384558080
            VITE_BACKEND_URI=
