# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and publish docker image

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: yarn
      - run: yarn run build
        env:
          VITE_REDIRECT_URI: "https://manosgr.me/"
          VITE_CLIENT_ID: "475749622384558080"
          VITE_BACKEND_URI: ""
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist

  push:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: dist
          name: build
      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v5.5
        with:
          # Name of the Docker image
          image: cube-bot-web
          # Target Docker registry
          registry: ghcr.io
          username: ${{ github.actor }}
          # Docker registry password
          password: ${{ secrets.GHCR_TOKEN }}
          # Adds latest tag to auto-generated GitOps tag
          addLatest: true
